spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labs
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
